version: '3.8'

services:
  # NestJS API
  nest-api:
    build: .
    ports:
      - '3000:3000'
    environment:
      - NODE_ENV=development
      - NLP_SERVICE_URL=http://nlp-service:8001
    depends_on:
      - nlp-service
    volumes:
      - .:/app
      - /app/node_modules
    networks:
      - nlp-network

  # Python NLP Microservice
  nlp-service:
    build: ./nlp-service
    ports:
      - '8001:8001'
    environment:
      - PYTHONUNBUFFERED=1
    volumes:
      - ./nlp-service:/app
    networks:
      - nlp-network
    deploy:
      resources:
        limits:
          memory: 4G
        reservations:
          memory: 2G

networks:
  nlp-network:
    driver: bridge
